<?php
return array (
  'web_ip' => '172.16.9.17',
  'db_type' => 'mysql',
  'db_host' => 'localhost',
  'db_name' => '532movie',
  'db_user' => 'root',
  'db_pwd' => 'wulang',
  'db_port' => '3306',
  'db_prefix' => 'gx_',
  'default_theme' => 'boostrap',
  'web_name' => '532movie',
  'web_url' => 'localhost/',
  'web_path' => '/532movie/',
  'web_hotkey' => '碟中谍4|泰坦尼克号|战马|',
  'web_keywords' => 'BNU校内电影分享站',
  'web_author' => 'wulang,yanhl',
  'web_description' => '532movie',
  'web_email' => 'wulang@mail.bnu.edu.cn',
  'web_qq' => '845428486',
  'web_copyright' => '',
  'web_tongji' => '',
  'web_icp' => '',
  'web_adsensepath' => 'temp/Banner',
  'web_admin_pagenum' => 20,
  'web_home_pagenum' => '5',
  'web_admin_hits' => 500,
  'web_hits_way' => '1',
  'web_hits_time' => 5,
  'web_admin_updown' => 100,
  'web_admin_score' => 9,
  'web_collect_num' => 2,
  'web_admin_edittime' => true,
  'web_admin_ordertype' => 'addtime',
  'web_admin_language' => '国语,粤语,英语,韩语,日语,法语,西班牙语,德语,泰语,意大利,语中文字幕,英文字幕',
  'web_admin_area' => '中国大陆,中国台湾,中国香港,韩国,日本,美国,英国,法国,意大利,德国,西班牙,泰国',
  'web_admin_nav' => 
  array (
    '网站信息配置' => '?s=Admin/Config/Conf/id/web',
    '视频数据管理' => '?s=Admin/Video/Show',
    '影片采集中心' => '?s=Admin/Collect/Show',
    '网站栏目管理' => '?s=Admin/Channel/Show',
    '网站广告管理' => '?s=Admin/Adsense/Show',
    '快捷菜单设置' => '?s=Admin/Config/Conf/id/nav',
  ),
  'upload_path' => 'uploads',
  'upload_style' => 'Y-m-d',
  'upload_thumb' => '0',
  'upload_thumb_w' => 120,
  'upload_thumb_h' => 168,
  'upload_water' => '0',
  'upload_water_img' => 'views/images/water.gif',
  'upload_water_pct' => 80,
  'upload_water_pos' => 9,
  'upload_http_down' => 10,
  'upload_http' => '0',
  'upload_ftp' => '0',
  'upload_ftp_host' => '255.255.255.255',
  'upload_ftp_user' => 'username',
  'upload_ftp_pass' => 'userpwd',
  'upload_ftp_port' => 21,
  'upload_ftp_dir' => '/',
  'upload_ftp_url' => '',
  'tmpl_cache_on' => false,
  'html_cache_on' => false,
  'html_cache_time' => 0,
  'html_read_type' => 0,
  'html_cache_index' => 1,
  'html_cache_list' => 1,
  'html_cache_content' => 1,
  'html_cache_play' => 1,
  'html_cache_mytpl' => '1',
  'url_html_suffix' => '.html',
  'html_file_suffix' => '.html',
  'url_rewrite' => '0',
  'url_html' => '0',
  'url_html_rule' => '2',
  'url_html_channel' => '0',
  'url_html_play' => '0',
  'url_create_time' => 2,
  'url_create_num' => 30,
  'url_dir_video' => 'vodlist',
  'url_dir_videoread' => 'detail',
  'url_dir_videoplay' => 'play',
  'url_dir_info' => 'infolist',
  'url_dir_inforead' => 'detail-n',
  'url_dir_special' => 'special',
  'url_dir_maps' => 'maps',
  'url_dir_all' => '',
  'user_register' => '1',
  'user_comment' => '1',
  'user_check' => '0',
  'user_pay' => '0',
  'user_post' => '0',
  'user_paycid' => 
  array (
    0 => '8',
    1 => '9',
    2 => '10',
    3 => '11',
    4 => '12',
    5 => '13',
    6 => '14',
    7 => '3',
    8 => '5',
    9 => '6',
  ),
  'user_money_play' => 1,
  'user_money_change' => 100,
  'user_money_add' => 50,
  'user_check_time' => 60,
  'user_page_cm' => 8,
  'user_page_gb' => 10,
  'user_replace' => '脏话|法轮功|枪械|A片|三级|伦理|毛片',
  '_htmls_' => 
  array (
    'home:index:index' => 
    array (
      0 => '{:action}',
      1 => 3600,
    ),
    'home:video:lists' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
    'home:info:lists' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
    'home:video:detail' => 
    array (
      0 => '{:module}_{:action}/{id|md5}',
      1 => 3600,
    ),
    'home:info:detail' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
    'home:video:play' => 
    array (
      0 => '{:module}_{:action}/{id|md5}',
      1 => 3600,
    ),
    'home:my:show' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
  ),
  'player_width' => 960,
  'player_height' => 550,
  'player_down' => '',
  'player_buffer' => '',
  'player_pause' => '',
  'player_time' => '0',
);
?>